// Dados mockados para migração inicial do Next.js
// Na etapa final, eles serão movidos para o Supabase

export const SPECS=[
  {id:'trauma',    nome:'Trauma',                c:'var(--c-trauma)',    label:'Trauma',
    lead:'Fixação, alongamento e reconstrução óssea — de ossos longos a pequenas correções — com implantes anatômicos e fixadores de última geração.',
    tec:['Placas anatômicas pré-moldadas','Fixadores externos circulares','Parafusos de compressão','Enxertos sintéticos'],
    pat:['Fraturas complexas','Deformidades ósseas','Pseudartrose','Alongamento ósseo'],
    proc:['Osteossíntese','Osteotomias','Artrodeses','Correção de deformidades'],
    dif:['Portfólio completo do membro superior ao inferior','Soluções estéreis prontas para uso','Compatibilidade com biológicos da casa']},
  {id:'bio',       nome:'Biológicos',            c:'var(--c-bio)',       label:'Biológicos',
    lead:'Substitutos ósseos e moduladores de regeneração que aceleram a consolidação e reduzem a necessidade de segunda cirurgia.',
    tec:['Vidro bioativo S53P4','β-TCP injetável','Géis barreira de aderência','Híbridos reforçados'],
    pat:['Defeitos e falhas ósseas','Não-consolidação','Aderências pós-cirúrgicas'],
    proc:['Enxertia óssea','Preenchimento de cavidades','Cirurgia de coluna e trauma'],
    dif:['Ação osteocondutora e antibacteriana','Aplicação direta, sem preparo','Endurecimento in situ']},
  {id:'artro',     nome:'Artroplastia',          c:'var(--c-artro)',     label:'Artroplastia',
    lead:'Implantes que restauram mobilidade e alinhamento articular — da mão ao retropé — com design anatômico e durabilidade comprovada.',
    tec:['Espaçadores em silicone','Parafusos canulados em titânio','Implantes de artrorrise'],
    pat:['Osteoartrite','Artrite reumatóide','Pé plano','Anquilose articular'],
    proc:['Artroplastia MCP/IFP','Artrorrise subtalar','Correção do pé plano'],
    dif:['Restauração do movimento natural','Titânio F-136 de alta resistência','Faixa completa de tamanhos']},
  {id:'dor',       nome:'Dor & Regenerativa',    c:'var(--c-dor)',       label:'Dor & Regenerativa',
    lead:'Manejo da dor e medicina regenerativa: viscossuplementação, radiofrequência e bloqueios para resolver causas e aliviar sintomas.',
    tec:['Viscossuplementação com AH','Radiofrequência pulsada','Manipulação de hemocomponentes'],
    pat:['Osteoartrite','Dor crônica articular','Patologias degenerativas','Neuropatias periféricas'],
    proc:['Infiltração intra-articular','Bloqueio de nervos','Procedimentos minimamente invasivos'],
    dif:['Ácido hialurônico não-animal','Alívio rápido e seguro','Kits estéreis prontos para uso']},
  {id:'esporte',   nome:'Medicina Esportiva',    c:'var(--c-esporte)',   label:'Medicina Esportiva',
    lead:'Reconstrução ligamentar e reparo de tecidos moles com âncoras flexíveis e implantes de fixação cortical para retorno seguro à atividade.',
    tec:['Âncoras de sutura flexível','Botões de fixação cortical','Suturas agulhadas'],
    pat:['Lesões de LCA/LCP','Instabilidade articular','Lesões do TFCC','Reinserções tendíneas'],
    proc:['Reconstrução ligamentar','Sutura artroscópica','Reparo do manguito rotador'],
    dif:['Versões SRT e STD de tensionamento','Faixa 1,6 a 2,5 mm','Cobertura de ombro a tornozelo']},
  {id:'pediatria', nome:'Ortopedia Pediátrica',  c:'var(--c-pediatria)', label:'Ortopedia Pediátrica',
    lead:'Implantes dimensionados para o esqueleto em crescimento — com perfil baixo, ângulos guiados e tecnologia de bloqueio para correções precisas.',
    tec:['Placas lâmina e bloqueadas','Bloqueio de ângulo variável','Implantes Low Profile'],
    pat:['Deformidades em varus/valgus','Pé torto congênito (PTC)','Pé plano','Pé de Charcot'],
    proc:['Osteotomias corretivas','Bloqueio de crescimento','Fusão colunar medial'],
    dif:['Liga de titânio ASTM F136','Ângulos de 80° a 150°','Versões direita e esquerda']},
  {id:'geral',     nome:'Ortopedia Geral',       c:'var(--c-geral)',     label:'Ortopedia Geral',
    lead:'Instrumental e tecnologias que elevam a precisão do gesto cirúrgico — microdissecção, aspiração, coleta de enxerto e fixação trocantérica.',
    tec:['Microdissecção','Aspiração integrada','Coleta de enxerto autólogo','Hastes TFN'],
    pat:['Fraturas de difícil redução','Síndrome do túnel do carpo','Fraturas femorais complexas'],
    proc:['Descompressão do túnel do carpo','Biópsia','Reconstrução articular'],
    dif:['Técnica minimamente invasiva','Reduz trauma às partes moles','Estéril, pronto para uso']},
  {id:'coluna',    nome:'Coluna',                c:'var(--c-coluna)',    label:'Coluna',
    lead:'Tecnologias para cirurgia de coluna — foco em segurança neural e campo cirúrgico limpo durante procedimentos vertebrais e cranianos.',
    tec:['Monitoramento de nervos','Estimulação controlada','Aspiração integrada'],
    pat:['Compressões neurais','Patologias vertebrais','Procedimentos cranianos'],
    proc:['Cirurgia de coluna','Descompressão','Fusão espinhal'],
    dif:['Reduz risco de complicação neural','Localização precisa de terminações nervosas','Campo livre de fluidos']},
  {id:'buco',      nome:'Bucomaxilo',            c:'var(--c-buco)',      label:'Bucomaxilo',
    lead:'Sistemas de fixação e reconstrução crânio-maxilo-facial — da cirurgia ortognática ao trauma de face — com instrumentação dedicada.',
    tec:['Sistemas 1.5 / 2.0 / 2.3 / 2.5','Fixação TriLock','Chave de inserção 90°'],
    pat:['Fraturas faciais','Deformidades dento-faciais','Reconstrução pós-ressecção'],
    proc:['Cirurgia ortognática','Osteotomias LeFort','Genioplastia','Reconstrução mandibular'],
    dif:['Codificação por cor 1.5/2.0','Instrumentação intraoral dedicada','Plataforma modular']},
];

export const TYPES = ['Implante','Instrumental','Consumível','Biológico','Tecnologia'];
export const BADGES = [{k:'novo',l:'Lançamentos'},{k:'top',l:'Mais vendidos'},{k:'premium',l:'Premium'},{k:'exclusivo',l:'Exclusivo'}];

export const INITIAL_PRODUCTS = [
 // ---------- TRAUMA ----------
 {id:'ocx',n:'Fixador Ósseo OCX',m:'OCX',e:'trauma',t:'Implante',tag:'Fixador ósseo estéril em titânio',
  d:['Redireciona o crescimento de ossos longos','Ponta lisa e estriada','Produto estéril, pronto para uso'],mat:'Titânio',rel:['veronafix','dynex','calcemex']},
 {id:'veronafix',n:'Veronafix',m:'Baide',e:'trauma',t:'Implante',tag:'Fraturas, alongamento e correção de ossos pequenos',
  ind:['Alongamento de metacarpo, metatarso, calcâneo e antebraço em pacientes pediátricos','Rigidez articular e fraturas cominutas intra-articulares','Artrodese da 1ª articulação carpo-metacarpiana com correção de tecido mole','Contraturas de mão e punho'],rel:['ocx','dynex']},
 {id:'loqteq',n:'Placas Anatômicas LOQTEQ',m:'LOQTEQ',e:'trauma',t:'Implante',tag:'Sistema de placas anatômicas pré-moldadas',
  d:['Clavícula e articulação acromioclavicular','Úmero e cotovelo','Fêmur distal','Tíbia proximal e distal','Osteotomia de joelho'],
  dif:['Anatomia específica por segmento','Reduz tempo cirúrgico de modelagem'],rel:['toolpro','toolvip','autograft','bpro'],b:['top']},
 {id:'toolvip',n:'Parafusos Tool VIP',m:'BRM Extremities',e:'trauma',t:'Implante',tag:'Parafusos estéreis em titânio',
  apl:['Osteotomia para correção de hállux valgo','Artrodese calcaneocuboide e talonavicular','Artrodeses interósseas na mão','Osteotomias mono e bicorticais no pé ou na mão','Fusão das articulações MTF1 e interfalangianas'],rel:['toolpro','loqteq']},
 {id:'toolpro',n:'Parafusos Tool Pro',m:'BRM Extremities',e:'trauma',t:'Implante',tag:'Compressão interfragmentária',
  d:['Disponíveis em 2 diâmetros e 2 tipos de rosca'],apl:['Artrodese do médio-pé','Artrodese talonavicular','Artrodese tíbio-tarsal','Osteotomia do calcâneo'],rel:['toolvip','loqteq']},
 {id:'calcemex',n:'Cal-Cemex®',m:'Tecres',e:'trauma',t:'Biológico',tag:'Enxerto ósseo β-TCP + PMMA',
  res:'Substituto ósseo reforçado, osteocondutivo e poroso, mecanicamente superior. A fórmula híbrida β-TCP + PMMA combina as vantagens de ambos os componentes.',rel:['bonalive','bpro','autograft'],b:['premium']},
 {id:'dynex',n:'Dynex',m:'—',e:'trauma',t:'Tecnologia',tag:'Fixador circular universal com extensão telescópica',
  res:'Sistema completo e inovador de fixação externa para estabilização de fraturas, osteotomias, artrodese de mediopé e retropé, alongamento ósseo (adulto e pediátrico) e correção de deformidades em membros superiores e inferiores.',
  d:['Compatível com diferentes tecnologias de fixação','Integra elementos tradicionais e modernos num único sistema'],rel:['ocx','veronafix'],b:['novo']},
 // ---------- BIOLÓGICOS ----------
 {id:'bonalive',n:'Bonalive',m:'BonAlive',e:'bio',t:'Biológico',tag:'Vidro bioativo S53P4',
  res:'Substituto otimizado do enxerto ósseo para cirurgia ortopédica, de trauma e da coluna.',
  d:['Granules — inibe naturalmente o crescimento bacteriano e estimula a formação óssea','Putty — altamente moldável, aplicação direta sem mistura','Putty MIS — posicionamento estável em cirurgia minimamente invasiva'],rel:['bpro','calcemex','autograft'],b:['premium']},
 {id:'bpro',n:'BPRO® Inject',m:'—',e:'bio',t:'Biológico',tag:'Enxerto ósseo de trifosfato de cálcio',
  res:'Dispositivo duplo (pó β-TCP + líquido endurecedor) que, ao ser misturado, forma uma pasta injetável e endurece em aproximadamente 6 minutos dentro do corpo. Substitui enxertos ósseos tradicionais sem necessidade de uma segunda cirurgia para remoção.',rel:['bonalive','calcemex']},
 {id:'betamix',n:'Betamix',m:'—',e:'bio',t:'Biológico',tag:'Gel barreira de aderência',
  d:['Barreira mecânica via gel de AH de alto peso molecular','Inibição da migração e proliferação de fibroblastos','Inibição da cascata de coagulação','Estímulo à regeneração fisiológica do tecido'],rel:['bonalive','bpro']},
 // ---------- ARTROPLASTIA ----------
 {id:'digitalis',n:'Digitalis',m:'BRM Extremities',e:'artro',t:'Implante',tag:'Implantes MCP e IFP em silicone',
  res:'Espaçadores elastoméricos de silicone para artroplastia das articulações metacarpofalângicas (MCP) e interfalângicas proximais (PIP), restaurando o movimento de flexão-extensão.',
  d:['Hastes com design anti-rotacional','Dobradiça com "T" dorsal contra hiperextensão','Mobilidade PIP 0–70° e MCP 0–90°'],rel:['silktoe','orbitron']},
 {id:'silktoe',n:'Silktoe',m:'BRM Extremities',e:'artro',t:'Implante',tag:'Implante para correção do pé plano',
  ind:['Osteoartrite','Artrite reumatóide','Superfícies articulares destruídas','Anquilose articular','Amplitude limitada de movimento'],rel:['orbitron','digitalis']},
 {id:'orbitron',n:'Orbitron',m:'BRM Extremities',e:'pediatria',t:'Implante',tag:'Parafuso subtalar para artrorrise',
  res:'Implante cônico e canulado em titânio (F-136), disponível em 6 tamanhos, para corrigir o pé plano em crianças e adultos. O design anatômico estabiliza a articulação subtalar, limita a pronação excessiva e restaura o arco plantar.',mat:'Titânio F-136',ap:'6 tamanhos',rel:['silktoe','bioplan']},
 // ---------- DOR & REGENERATIVA ----------
 {id:'foothl',n:'Kit Foot HL',m:'Larsson',e:'dor',t:'Instrumental',tag:'Tratamento cirúrgico de procedimentos do pé',
  ind:['Síndrome de Haglund','Exostoses interdigitais','Doença de Freiberg','Dedos em garra','Hállux rígido e hállux valgo (joanete)'],rel:['xeprf','toolvip']},
 {id:'xeprf',n:'Cânula XEPRF',m:'Sollievo',e:'dor',t:'Consumível',tag:'Introdutor canulado para radiofrequência',
  d:['Cânula-guia com eletrodo e guia de medicação','Precisa, sem risco de deslocamentos','Estéril e descartável','Exclusiva para bloqueio e radiofrequência pulsada','Comprimentos 5/10/15 cm · ponta ativa 5 e 10 mm'],rel:['biopain']},
 {id:'biopain',n:'Kit Biopain MRI',m:'Larsson',e:'dor',t:'Instrumental',tag:'Bloqueio de dor em nervos periféricos',
  d:['Coleta de enxerto autólogo ou alogênico','Tratamento da dor em patologias degenerativas','Aporte na manipulação de hemocomponentes','Homogeneização e emulsificação'],rel:['xeprf']},
 // ---------- MEDICINA ESPORTIVA ----------
 {id:'ffanchor',n:'FastFit Anchor',m:'Razek',e:'esporte',t:'Implante',tag:'Âncoras de sutura flexível',
  d:['1,6 mm — ombro, cotovelo, quadril, pé e tornozelo','2,0 mm — ombro e cotovelo','2,5 mm — ombro e cotovelo'],rel:['ffbutton','suturfix']},
 {id:'ffbutton',n:'FastFit Button',m:'Razek',e:'esporte',t:'Implante',tag:'Implante para reconstrução ligamentar',
  d:['Lesões de LCA/LCP e reinserção de tecidos moles','Versão SRT — tração convencional via córtex','Versão STD — tensionamento na direção do túnel ósseo'],mat:'Liga de titânio F-136',rel:['ffanchor','suturfix']},
 {id:'tfckit',n:'TFC Kit',m:'Razek',e:'esporte',t:'Instrumental',tag:'Sutura do complexo da fibrocartilagem triangular (TFCC)',
  res:'Auxilia a realização da sutura do TFCC em cirurgias minimamente invasivas, com ganchos de passagem dedicados.',rel:['suturfix','ffanchor']},
 {id:'suturfix',n:'Suturfix',m:'Sartori',e:'esporte',t:'Consumível',tag:'Sutura cirúrgica agulhada',
  d:['Agulha curva atraumática cilíndrica ½ círculo — 20 e 25 mm','Agulha reta atraumática cilíndrica — 255 mm'],rel:['ffanchor','ffbutton']},
 // ---------- PEDIATRIA ----------
 {id:'placalamina',n:'Placas Lâmina',m:'TechImport',e:'pediatria',t:'Implante',tag:'Implantes pediátricos para osteotomias e fraturas',
  d:['Tamanhos 3,5 e 5,0 mm','Indicação para fêmur proximal','Modelos 130° (3 furos) e 90° (3 furos)'],mat:'Liga de titânio ASTM F136',rel:['placabloq35','placaie8']},
 {id:'placabloq35',n:'Placas Bloqueadas 3,5 / 5,0',m:'TechImport',e:'pediatria',t:'Implante',tag:'Pediátricas bloqueadas',
  d:['Fêmur e tíbia, proximal e distal','Parafusos com avanço duplo de rosca','Angulações de 80° a 150° para varus e valgus'],mat:'Liga de titânio ASTM F136',rel:['placabloq27','placalamina']},
 {id:'placabloq27',n:'Placas Bloqueadas 2,7',m:'TechImport',e:'pediatria',t:'Implante',tag:'Bloqueio com ângulo variável',
  d:['Fêmur proximal, tíbia proximal e distal','Bloqueio de ângulo variável até 15° fora do eixo','Placa medial: 2 a 12 furos','Placa lateral: 4 a 16 furos'],rel:['placabloq35','placaie8']},
 {id:'placaie8',n:'Placas I E 8',m:'TechImport',e:'pediatria',t:'Implante',tag:'Bloqueio de crescimento e correção',
  d:['Correção de deformidades ósseas','Bloqueio do crescimento ósseo','Versões não-bloqueadas para movimentação','Perfil Low Profile, menor protrusão'],rel:['placalamina','placabloq35']},
 {id:'bioplan',n:'Bioplan',m:'BRM Extremities',e:'pediatria',t:'Implante',tag:'Implante para correção do pé plano',
  res:'Parafuso para artrorrise em correção do pé plano, disponível em faixa completa de diâmetros e comprimentos.',
  cod:[['BRSBIOP0713P','7,0 × 13 mm'],['BRSBIOP0814P','8,0 × 14 mm'],['BRSBIOP0915P','9,0 × 15 mm'],['BRSBIOP1016P','10,0 × 16 mm'],['BRSBIOP1117P','11,0 × 17 mm'],['BRSBIOP1218P','12,0 × 18 mm'],['BRSBIOP1319P','13,0 × 19 mm']],rel:['orbitron','nitfix']},
 {id:'nitfix',n:'Nitfix',m:'Razek',e:'pediatria',t:'Implante',tag:'Grampo de fixação para extremidades',
  d:['Osteossíntese em fraturas, osteotomias e artrodeses','Fixação dos ossos das extremidades superiores e inferiores','Design de perfil baixo, menor irritação dos tecidos moles','Compressão óssea constante após implantado'],rel:['placalamina','tendao']},
 {id:'tendao',n:'Kit Transferência de Tendão',m:'ImplanFix',e:'pediatria',t:'Instrumental',tag:'Pé torto congênito (PTC)',
  res:'Instrumental cirúrgico cortante que auxilia a passagem da sutura no tratamento pediátrico do pé torto congênito (PTC).',rel:['placamcf','nitfix']},
 {id:'placamcf',n:'Placa MCF',m:'ImplanFix',e:'pediatria',t:'Implante',tag:'Fusão colunar medial · pé de Charcot',
  d:['Fusão de navicular, cuneiforme medial e 1º metatarso','Espessura 1,4 mm','Tamanhos P e M','Versões direita e esquerda'],rel:['tendao','placabloq35']},
 // ---------- ORTOPEDIA GERAL ----------
 {id:'nanoblade',n:'Nano Blade',m:'Smart Surgical',e:'geral',t:'Instrumental',tag:'Microdissecção',
  d:['NanoBlade35 — lâmina de 3 mm para cortes de profundidade e angulação precisas','Cystout Blade — dupla lâmina afiada para descolamento fino','NanoCut ABS — dissecção fina de tecidos moles em microcirurgia'],rel:['ultraknife','ctsurgery']},
 {id:'ctsurgery',n:'Kit CT Surgery',m:'MJ',e:'geral',t:'Instrumental',tag:'Descompressão do ligamento transverso do carpo',
  res:'Desobstrução e ressecção do ligamento transverso do carpo (L.T.C.) através do túnel do carpo, por técnica minimamente invasiva.',rel:['buttonfech','ultraknife']},
 {id:'buttonfech',n:'Button de Fechamento',m:'MJ',e:'geral',t:'Implante',tag:'Preserva a integridade do enxerto',
  d:['Impede o refluxo do enxerto para partes moles','Mantém o material no local desejado','Garante a reconstrução do estojo ósseo fisiológico'],rel:['ctsurgery','osteoinject']},
 {id:'cleanup',n:'CleanUp Pro',m:'MJ',e:'geral',t:'Consumível',tag:'Tratamento de feridas e queimaduras',
  d:['Irrigação, limpeza e desbridamento de feridas agudas, crônicas e queimaduras','Produto de uso único e descartável','Esterilizado por óxido de etileno · validade de 2 anos'],rel:['flush','davtom']},
 {id:'ultraknife',n:'Kit UltraKnife Mini',m:'MJ',e:'geral',t:'Instrumental',tag:'Liberação da polia anular flexora',
  d:['Pequenas incisões','Monitoramento visual por ultrassom','Pronto para uso em cirurgia','Estéril, minimiza riscos de contaminação'],rel:['nanoblade','ctsurgery']},
 {id:'flush',n:'Ponteira Flush',m:'Razek',e:'geral',t:'Consumível',tag:'Aspiração de líquidos e fumaça',
  res:'Irrigação e sucção integradas e controladas pelo cirurgião, minimizando a fumaça no campo cirúrgico e refrigerando tecidos adjacentes.',rel:['davtom','cleanup']},
 {id:'davtom',n:'Davtom',m:'HCS',e:'geral',t:'Instrumental',tag:'Aspiração a vácuo de tecidos para biópsia',
  res:'Aspiração a vácuo de tecidos ósseos e moles utilizada para biópsia. Fornecido estéril (ETO), pronto para uso.',rel:['flush','autograft']},
 {id:'insidecore',n:'InsideCore Revolution',m:'MJ',e:'geral',t:'Instrumental',tag:'Fraturas articulares de difícil redução',
  d:['Lâmina flexível expansível, acesso paralelo à articulação','Instrumentação vertical do fragmento para redução','Reduções precisas com menor impacto nas partes moles'],rel:['osteoinject','loqteq']},
 {id:'osteoinject',n:'OsteoInject Precision',m:'MJ',e:'geral',t:'Instrumental',tag:'Aplicação precisa de enxertos ósseos',
  d:['Aplicação controlada em áreas de difícil acesso','Reduz a perda de material e o trauma às partes moles','Favorece recuperação mais rápida com menos complicações'],rel:['insidecore','autograft']},
 {id:'autograft',n:'Autograft',m:'Luniv',e:'geral',t:'Instrumental',tag:'Coleta de enxertia óssea e desbridamento',
  d:['Ação osteogênica, osteoindutora e osteocondutora do enxerto autólogo','Uso combinado com β-TCP, hidroxiapatita, osso desmineralizado e colágeno'],rel:['bison','bonalive','bpro']},
 {id:'bison',n:'Bison TFN',m:'Luniv',e:'geral',t:'Implante',tag:'Haste de fixação trocantérica',
  res:'Sistema BISON™ TFN com design anatômico, opções de bloqueio guiadas com precisão e forte engajamento no osso esponjoso, desenvolvido para tratar fraturas femorais complexas.',
  d:['Ideal para estabilidade em fraturas intertrocantéricas e subtrocantéricas'],rel:['autograft','loqteq'],b:['top']},
 // ---------- BUCOMAXILO ----------
 {id:'ortognatica',n:'Ortognática 1.5 / 2.0 · IMF 2.0',m:'Medartis',e:'buco',t:'Implante',tag:'Osteotomias mandibulares e maxilares',
  d:['LeFort I, II e III','Osteotomia dos ramos e corpo mandibular','Genioplastias'],rel:['trilock','traumabuco']},
 {id:'trilock',n:'TriLock 2.0/2.3/2.5 · Reco 2.5',m:'Medartis',e:'buco',t:'Implante',tag:'Fixação, osteotomias e reconstrução',
  d:['Fraturas do côndilo, ângulo, sínfise e mandíbula atrófica','Ressecção tumoral, de osteorradionecrose e de osteomielite','Remoção de placas convencionais fraturadas'],rel:['ortognatica','chave90']},
 {id:'traumabuco',n:'Trauma 1.5 / 2.0',m:'Medartis',e:'buco',t:'Implante',tag:'Fixação de fraturas faciais',
  d:['Fraturas cranianas e da face média','Fraturas maxilo-faciais, centrais e laterais','Osteotomias maxilares'],rel:['ortognatica','chave90']},
 {id:'chave90',n:'Sistema de Chave 90°',m:'Medartis',e:'buco',t:'Instrumental',tag:'Perfuração e inserção intraoral de parafuso',
  d:['Cabo de rotação e garfo de suporte','Também funciona como perfurador','Lâminas e brocas codificadas por cor para sistemas 1.5 e 2.0 mm'],rel:['trilock','traumabuco']},
 // ---------- LUNIV ENDO SCIENCES ----------
 // Dor & Regenerativa
 {id:'accessrecovery',n:'Access Recovery',m:'Luniv',e:'dor',t:'Instrumental',tag:'Conjunto para procedimentos percutâneos e intraósseos',
  res:'Conjunto cirúrgico projetado para subcondroplastia, viscossuplementação em pacientes com dor crônica e intervenções percutâneas e intraósseas guiadas por ultrassom.',rel:['easyaccess','nanofat','xeprf']},
 {id:'nanofat',n:'NanoFat',m:'Luniv',e:'dor',t:'Instrumental',tag:'Aspiração, processamento e enxerto de tecido adiposo autólogo',
  res:'Dispositivo destinado à aspiração, processamento e enxerto de tecido adiposo autólogo para microenxertos, com aplicações em ortopedia, medicina esportiva e terapias regenerativas.',
  ind:['Regeneração de cartilagem','Osteocondroplastia','Artrites e dor crônica','Outras patologias articulares'],rel:['adinizer','accessrecovery','easyaccess']},
 {id:'adinizer',n:'Adinizer Smart Kit',m:'Luniv',e:'dor',t:'Consumível',tag:'Processamento e micronização de tecido adiposo autólogo',
  res:'Processa o tecido adiposo do próprio paciente; os filtros dos processadores possuem lâminas que micronizam a gordura para microenxertos e regeneração.',
  ind:['Ortopedia','Tratamento de feridas','Estética'],rel:['nanofat','accessrecovery']},
 {id:'easyaccess',n:'Easy Access Kit',m:'Luniv',e:'dor',t:'Consumível',tag:'Cânulas de uso único para procedimentos percutâneos e intraósseos',
  res:'Kit de cânulas de uso único para osteocondroplastia, subcondroplastia e viscossuplementação, com intervenções auxiliadas por ultrassom através de cânula sonovisível.',
  d:['Aplicação de enxerto ósseo em pasta','Extração, coleta e preparo de fluidos e biópsias','Regiões vertebrais, articulares, pélvicas e da coluna'],rel:['accessrecovery','nanofat','autograft']},
 // Ortopedia Geral
 {id:'easyjet',n:'EasyJet',m:'Luniv',e:'geral',t:'Instrumental',tag:'Irrigação e aspiração manual de cavidades ósseas',
  res:'Dispositivo para assepsia de cavidades intra e extraósseas, oferecendo irrigação e aspiração de fluidos por operação manual.',rel:['smartclean','colibri','cleanup']},
 {id:'smartclean',n:'SmartClean',m:'Luniv',e:'geral',t:'Consumível',tag:'Irrigação com escova de desbridamento e aspiração',
  res:'Combina a ação da irrigação à remoção de tecidos mais difíceis com escova de desbridamento, aspirando o fluido e os resíduos da ferida.',rel:['easyjet','cleanup','saferelease']},
 {id:'saferelease',n:'SafeRelease TCG',m:'Luniv',e:'geral',t:'Instrumental',tag:'Descompressão de tecidos moles',
  res:'Destinado a procedimentos de descompressão de síndromes ou inflamações de tecidos moles, restaurando a elasticidade através de ressecções ou criação de canais.',rel:['ultraknife','ctsurgery']},
 {id:'colibri',n:'Colibri',m:'Luniv',e:'geral',t:'Consumível',tag:'Aspiração e irrigação para cirurgia geral e laparoscópica',
  res:'Dispositivo estéril de uso único para cirurgias gerais e laparoscópicas; realiza aspiração, irrigação ou ambas, com ângulo da cânula de irrigação ajustável.',rel:['easyjet','smartclean','flush']},
 {id:'istimext',n:'I-Stim Ext',m:'Luniv',e:'geral',t:'Tecnologia',tag:'Localização e monitoramento de nervos periféricos',
  res:'Localiza, identifica, estimula e monitora nervos em procedimentos das extremidades; detecta a integridade do nervo no campo cirúrgico, ajudando a identificar áreas seguras para manipulação.',rel:['istimbhn','istimspine']},
 {id:'assistfix',n:'AssistFix',m:'Luniv',e:'geral',t:'Instrumental',tag:'Alinhamento e preparo de leito ósseo',
  res:'Auxilia no alinhamento, direcionamento temporário e preparo de leito ósseo (decorticação, raspagem e desbridamento).',
  ind:['Fusão óssea e artrodese','Correção de desvios anatômicos','Pseudartroses e osteotomias'],rel:['autograft','easyaccess']},
 // Bucomaxilo
 {id:'istimbhn',n:'I-Stim BHN',m:'Luniv',e:'buco',t:'Tecnologia',tag:'Localização e monitoramento de nervos em bucomaxilo',
  res:'Localiza, identifica, estimula e monitora nervos em procedimentos bucomaxilofaciais; detecta a integridade original do nervo no local cirúrgico para a segurança do paciente.',rel:['istimext','istimspine']},
 // Coluna
 {id:'istimspine',n:'I-Stim Spine',m:'Luniv',e:'coluna',t:'Tecnologia',tag:'Monitoramento de nervos em cirurgia de coluna',
  res:'Promove a localização de terminações nervosas por estímulos controlados, reduzindo a possibilidade de complicações em coluna e crânio; inclui cânula de aspiração para manter a região livre de fluidos.',rel:['istimext','istimbhn']},
 // ---------- BUCOMAXILO · Biomateriais (linha Purgo / Implantec) ----------
 {id:'thegraft',n:'THE Graft Collagen',m:'Purgo',e:'buco',t:'Biológico',tag:'Enxerto ósseo porcino com colágeno',mat:'Osso porcino + colágeno',
  res:'Matriz óssea mineral natural e porosa de origem porcina, combinada a colágeno para fácil manuseio e moldagem no defeito ósseo.',
  d:['Origem porcina desproteinizada','Colágeno para fácil manuseio','Estrutura porosa osteocondutora','Apresentação: bloco · grânulos cancellous'],rel:['biocover','thecoverflex','thegraftpart'],b:['premium']},
 {id:'thegraftring',n:'THE Graft Bone Ring',m:'Purgo',e:'buco',t:'Biológico',tag:'Enxerto ósseo porcino para técnica de Bone Ring',mat:'Osso porcino',
  res:'Bloco de matriz óssea mineral porcina no formato de anel, para a técnica de Bone Ring em reconstrução e ganho ósseo.',
  d:['Formato em anel (Bone Ring)','Matriz óssea porcina porosa','Osteocondução para reconstrução'],rel:['thegraft','thecoverflex']},
 {id:'thegraftpart',n:'THE Graft Particulado',m:'Purgo',e:'buco',t:'Biológico',tag:'Enxerto ósseo porcino particulado em frasco',mat:'Osso porcino',
  res:'Matriz óssea mineral natural e porosa de origem porcina, em grânulos, para preenchimento de defeitos e regeneração óssea.',
  d:['Grânulos cancellous','Estrutura porosa osteocondutora','Apresentação: frasco · SMALL 0,25–1 mm · LARGE 1–2 mm'],rel:['thegraft','thegraftsyr','biocover']},
 {id:'thegraftsyr',n:'THE Graft Seringa',m:'Purgo',e:'buco',t:'Biológico',tag:'Enxerto ósseo porcino pré-carregado em seringa',mat:'Osso porcino',
  res:'Matriz óssea mineral porcina em grânulos, pré-carregada em seringa para aplicação direta e controlada no defeito.',
  d:['Aplicação direta e controlada','Pronto para uso','Apresentação: seringa · 0,25–1 mm'],rel:['thegraftpart','thegraft']},
 {id:'biotex',n:'Sutura PTFE Biotex',m:'Purgo',e:'buco',t:'Consumível',tag:'Fio de sutura de PTFE para cirurgia de implantes',mat:'PTFE (monofilamento)',
  res:'Fio de sutura monofilamentar de PTFE (PFOA-free), não absorvível, indicado para cirurgia de implantes e procedimentos bucomaxilares.',
  d:['Monofilamento de PTFE não absorvível','Baixa adesão bacteriana','Agulha reverse cutting','Apresentação: 3-0 · 4-0 · 5-0 · caixa com 10 unidades'],rel:['opentex','thecoverflex']},
 {id:'biocover',n:'BioCover',m:'Purgo',e:'buco',t:'Biológico',tag:'Membrana de colágeno reabsorvível',mat:'Colágeno reabsorvível',
  res:'Membrana de colágeno reabsorvível para regeneração óssea e tecidual guiada, protegendo o enxerto durante a cicatrização.',
  d:['Colágeno reabsorvível','Regeneração óssea/tecidual guiada','Proteção do enxerto'],rel:['thegraft','thecoverflex','thegraftpart']},
 {id:'thecoverflex',n:'THE Cover Flex',m:'Purgo',e:'buco',t:'Biológico',tag:'Membrana de colágeno absorvível porcina',mat:'Colágeno porcino',
  res:'Membrana de colágeno absorvível de origem porcina, flexível, para regeneração óssea guiada e cobertura de enxertos.',
  d:['Colágeno porcino absorvível','Flexível e adaptável','Cobertura de enxertos'],rel:['thegraft','biocover','thegraftring']},
 {id:'opentex',n:'Membrana OpenTex PTFE',m:'Purgo',e:'buco',t:'Consumível',tag:'Membrana de PTFE não absorvível',mat:'PTFE',
  res:'Membrana de politetrafluoretileno (PTFE) puro, porosa e não absorvível, para regeneração óssea guiada.',
  d:['PTFE puro não absorvível','Estrutura porosa','Regeneração óssea guiada'],rel:['opentextr','biotex']},
 {id:'opentextr',n:'Membrana OpenTex TR',m:'Purgo',e:'buco',t:'Consumível',tag:'Membrana de PTFE com reforço de titânio',mat:'PTFE + titânio',
  res:'Membrana de PTFE não absorvível com reforço de titânio, para manutenção de espaço em defeitos amplos e reconstruções verticais.',
  d:['Reforço de titânio','Manutenção de espaço','Defeitos amplos / reconstrução vertical'],rel:['opentex','thegraftring'],b:['premium']},
];

export const UFS = ['PE','PB','RN','CE','PI','MA','PA'];

export const INITIAL_IMG = {
  "ocx": "ocx.jpg", "veronafix": "veronafix.jpg", "loqteq": "loqteq.jpg", "toolvip": "toolvip.jpg",
  "toolpro": "toolpro.jpg", "calcemex": "calcemex.jpg", "dynex": "dynex.jpg", "bonalive": "bonalive.jpg",
  "bpro": "bpro.jpg", "betamix": "betamix.jpg", "digitalis": "digitalis.jpg", "silktoe": "silktoe.jpg",
  "orbitron": "orbitron.jpg", "foothl": "foothl.jpg", "xeprf": "xeprf.jpg", "biopain": "biopain.jpg",
  "ffanchor": "ffanchor.jpg", "ffbutton": "ffbutton.jpg", "tfckit": "tfckit.jpg", "suturfix": "suturfix.jpg",
  "placalamina": "placalamina.jpg", "placabloq35": "placabloq35.jpg", "placabloq27": "placabloq27.jpg",
  "placaie8": "placaie8.jpg", "bioplan": "bioplan.jpg", "nitfix": "nitfix.jpg", "tendao": "tendao.jpg",
  "placamcf": "placamcf.jpg", "nanoblade": "nanoblade.jpg", "ctsurgery": "ctsurgery.jpg",
  "buttonfech": "buttonfech.jpg", "cleanup": "cleanup.jpg", "ultraknife": "ultraknife.jpg",
  "flush": "flush.jpg", "davtom": "davtom.jpg", "insidecore": "insidecore.jpg",
  "osteoinject": "osteoinject.jpg", "autograft": "autograft.jpg", "bison": "bison.jpg",
  "ortognatica": "ortognatica.jpg", "trilock": "trilock.jpg", "traumabuco": "traumabuco.jpg",
  "chave90": "chave90.jpg", "accessrecovery": "accessrecovery.jpg", "nanofat": "nanofat.jpg",
  "adinizer": "adinizer.jpg", "easyaccess": "easyaccess.jpg", "easyjet": "easyjet.jpg",
  "smartclean": "smartclean.jpg", "saferelease": "saferelease.jpg", "colibri": "colibri.jpg",
  "istimext": "istimext.jpg", "assistfix": "assistfix.jpg", "istimbhn": "istimbhn.jpg",
  "istimspine": "istimspine.jpg", "thegraft": "thegraft.jpg", "thegraftring": "thegraftring.jpg",
  "thegraftpart": "thegraftpart.jpg", "thegraftsyr": "thegraftsyr.jpg", "biotex": "biotex.jpg",
  "biocover": "biocover.jpg", "thecoverflex": "thecoverflex.jpg", "opentex": "opentex.jpg",
  "opentextr": "opentextr.jpg"
};

export const INITIAL_UF = {
  ocx: ['PE', 'RN'], loqteq: ['PE', 'CE'], dynex: ['RN', 'PB'], bonalive: ['PE', 'RN', 'CE'],
  bioplan: ['PE'], bison: ['CE', 'MA']
};

export const ICN={
  check:'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>',
  plus:'<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></svg>',
  arrow:'<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',
  copy:'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.1" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="12" height="12" rx="2.5"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>',
  share:'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.1" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 13.5 6.8 4M15.4 6.5 8.6 10.5"/></svg>',
  star:'<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2.5l2.9 5.9 6.5.9-4.7 4.6 1.1 6.5L12 17.8 6.2 20.9l1.1-6.5L2.6 9.8l6.5-.9L12 2.5Z"/></svg>',
  pin:'<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>',
  doc:'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M9 13h6M9 17h4"/></svg>',
};

export const badgeMeta={novo:{cls:'novo',l:'Lançamento'},top:{cls:'top',l:'Mais vendido'},premium:{cls:'premium',l:'Premium'},exclusivo:{cls:'excl',l:'★ Exclusivo'}};
